name: Tagged Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-reusable-release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      snapshot: false
    secrets: inherit
