name: Release Preview

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "*.md"
  workflow_dispatch:

jobs:
  call-reusable-release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      snapshot: true
